{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.datasetUpload.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-dataset-upload
data:
  dataset-upload.jsonnet: {{ tpl (.Files.Get "hooks/dataset-upload/dataset-upload.jsonnet") . | quote }}
{{- end }}
{{- end }}
