{{- if eq (include "primehub-usage.enabled" .) "true" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "primehub-usage.name" . }}-db
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs:
  - list
- apiGroups:
  - primehub.io
  resources:
  - phjobs
  - phdeployments
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "primehub-usage.name" . }}-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "primehub-usage.name" . }}-db
subjects:
- kind: ServiceAccount
  name: {{ include "primehub-usage.name" . }}-db
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "primehub-usage.name" . }}-db
{{- end }}
