# this should be deregistered once the controller stops
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-rclone
spec:
  attachRequired: true
  podInfoOnMount: false  # are we sure about this?
