#! /bin/sh
#
# Usage: run-app <command> <args>
#

# Configurable variable
PRIMEHUB_APP_ID=${PRIMEHUB_APP_ID}
PRIMEHUB_APP_ROOT=${PRIMEHUB_APP_ROOT}
PRIMEHUB_APP_BASE_URL=${PRIMEHUB_APP_BASE_URL}

# Prepare PrimeHub App Root
mkdir -p ${PRIMEHUB_APP_ROOT}

# Run Command
exec "$@"
rc=$?

exit ${rc}
