{{- if .Values.graphql.image.credentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "primehub.graphql.pullSecret" . }}
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-graphql-pull-secret
type: kubernetes.io/dockerconfigjson
{{- end }}
---
{{- if .Values.graphql.sharedGraphqlSecret }}
apiVersion: v1
data:
  graphql-secret: {{ .Values.graphql.sharedGraphqlSecret | b64enc }}
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-graphql-shared-secret
type: Opaque
{{- end }}
