apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instancetypes.primehub.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: primehub.io
  version: v1alpha1
  names:
    kind: InstanceType
    plural: instancetypes
  scope: Namespaced
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        spec:
          type: object
          properties:
            description:
              type: string
            displayName:
              type: string
            limits.cpu:
              type: number
            limits.memory:
              type: string
            limits.nvidia.com/gpu:
              type: integer
            requests.cpu:
              type: number
            request.memory:
              type: string
          required:
            - limits.cpu
            - limits.memory
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datasets.primehub.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.type
      name: Type
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: primehub.io
  version: v1alpha1
  names:
    kind: Dataset
    plural: datasets
  scope: Namespaced
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
            annotations:
              type: object
              properties:
                dataset.primehub.io/homeSymlink:
                  type: string
                  pattern: '^(true|false|yes|no)$'
                dataset.primehub.io/launchGroupOnly:
                  type: string
                  pattern: '^(true|false|yes|no)$'
                dataset.primehub.io/mountRoot:
                  type: string
          required:
            - name
        spec:
          type: object
          properties:
            description:
              type: string
            displayName:
              type: string
            gitsync:
              type: object
              properties:
                secret:
                  type: string
            type:
              type: string
              pattern: '^(env|git|pv|hostPath|nfs)$'
            url:
              type: string
            variables:
              type: object
            volumeName:
              type: string
            pv:
              type: object
              properties:
                provisioning:
                  type: string
                  pattern: '^(auto|manual)$'
            hostPath:
              type: object
              properties:
                path:
                  type: string
              required:
                - path
            nfs:
              type: object
              properties:
                server: 
                  type: string
                path:
                  type: string
              required:
                - server
                - path
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.primehub.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: primehub.io
  version: v1alpha1
  names:
    kind: Image
    plural: images
  scope: Namespaced
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        spec:
          type: object
          properties:
            description:
              type: string
            displayName:
              type: string
            pullSecret:
              type: string
            url:
              type: string
