{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.datasetUpload.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primehub-dataset-upload
spec:
  replicas: {{ .Values.datasetUpload.metacontrollerHooks.replicas }}
  selector:
    matchLabels:
      app: primehub-dataset-upload
  template:
    metadata:
      labels:
        app: primehub-dataset-upload
      annotations:
        sidecar.istio.io/inject: "false"
        checksum/config: {{ tpl (.Files.Glob "hooks/dataset-upload/*").AsConfig . | nindent 2 | sha256sum }}
    spec:
      containers:
      - name: hooks
        image: "{{ .Values.datasetUpload.metacontrollerHooks.image.repository }}:{{ .Values.datasetUpload.metacontrollerHooks.image.tag }}"
        imagePullPolicy: {{ .Values.datasetUpload.metacontrollerHooks.image.pullPolicy }}
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        resources:
{{ toYaml .Values.datasetUpload.metacontrollerHooks.resources | indent 10 }}
      volumes:
      - name: hooks
        configMap:
          name: primehub-dataset-upload
{{- end }}
{{- end }}
