{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.datasetUpload.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: primehub-dataset-upload
spec:
  selector:
    app: primehub-dataset-upload
  ports:
  - port: 80
    targetPort: 8080
{{- end }}
{{- end }}
