{{- if .Values.keycloak.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.name" $ }}-admin-creds
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.keycloak.username | quote }}
  password: {{ .Values.keycloak.password | quote }}
{{- end }}
