{{- if .Values.keycloak.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.name" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.keycloak.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
{{- end }}
