{{- if .Values.keycloak.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.name" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.keycloak.service.httpsPort }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
{{- end }}
