{{- if or (eq .Values.primehub.mode "ee") (eq .Values.primehub.mode "deploy") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "primehub.name" . }}-controller
    helm.sh/chart: {{ include "primehub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "primehub.fullname" . }}-controller
  namespace: {{ .Release.Namaspece }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "primehub.fullname" . }}-controller-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "primehub.fullname" . }}-controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "extensions"
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - imagespecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "primehub.fullname" . }}-controller-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "primehub.fullname" . }}-controller-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "primehub.fullname" . }}-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "primehub.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "primehub.fullname" . }}-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "primehub.fullname" . }}-controller-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "primehub.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "primehub.fullname" . }}-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "primehub.fullname" . }}-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "primehub.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
{{- end }}
