{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.gitsync.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primehub-gitsync
spec:
  replicas: {{ .Values.gitsync.replicas }}
  selector:
    matchLabels:
      app: primehub-gitsync
  template:
    metadata:
      labels:
        app: primehub-gitsync
        role: webhook-server
      annotations:
        sidecar.istio.io/inject: "false"
        checksum/config: {{ tpl (.Files.Glob "hooks/gitsync/*").AsConfig . | nindent 2 | sha256sum }}
    spec:
      containers:
      - name: hooks
        image: "{{ .Values.gitsync.image.repository }}:{{ .Values.gitsync.image.tag }}"
        imagePullPolicy: {{ .Values.gitsync.image.pullPolicy }}
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        resources:
{{ toYaml .Values.gitsync.resources | indent 10 }}
    {{- with .Values.gitsync.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.gitsync.affinity }}
      affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.gitsync.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
      volumes:
      - name: hooks
        configMap:
          name: primehub-gitsync
{{- end }}
{{- end }}
