{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.gitsync.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: primehub-gitsync
spec:
  selector:
    app: primehub-gitsync
    role: webhook-server
  ports:
  - port: 80
    targetPort: 8080
{{- end }}
{{- end }}
