version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "d0:90:27:9c:dc:28:b5:3e:d8:18:0c:9a:64:46:6f:d4"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}

      - run:
          name: publish
          command: |
            ./ci/publish.sh

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"

workflows:
  version: 2
  latest_builds:
    jobs:
      - build:
          filters:
            branches:
              only: master
  release_builds:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
