{{- if .Values.admission.enabled }}
{{- $ca := genCA "pod-image-replacing-webhook-certs" 3650 }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-image-mutating-webhook
webhooks:
  - name: pod-image-mutating-webhook.primehub.io
    sideEffects: None
    clientConfig:
      service:
        name: pod-image-replacing-webhook-svc
        namespace: {{ .Release.Namespace }}
        path: "/image-mutation"
      caBundle: {{ $ca.Cert | b64enc }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        primehub.io/image-mutation-webhook: "enabled"
---
{{- $cn := "pod-image-replacing-webhook-svc" }}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $altNames := (list $altName1 $altName2) }}
{{- $cert := genSignedCert $cn nil $altNames 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: pod-image-replacing-webhook-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cert.pem: {{ $cert.Cert | b64enc }}
  key.pem: {{ $cert.Key | b64enc }}
{{- end }}