{{- if .Values.admission.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: resources-validation-webhook
  name: resources-validation-webhook-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: resources-validation-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod-image-replacing-webhook
  name: pod-image-replacing-webhook-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: pod-image-replacing-webhook
  sessionAffinity: None
  type: ClusterIP
{{- end }}