apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "primehub.name" . }}-graphql
rules:
- apiGroups:
  - primehub.io
  resources:
  - instancetypes
  - images
  - datasets
  - imagespecs
  - imagespecjobs
  - phjobs
  - phschedules
  - phdeployments
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
  - patch
- apiGroups: [""]
  resources:
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
  - patch
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "primehub.name" . }}-graphql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "primehub.name" . }}-graphql
subjects:
- kind: ServiceAccount
  name: {{ include "primehub.name" . }}-graphql
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "primehub.name" . }}-graphql
  labels:
    app: {{ include "primehub.name" . }}
    chart: {{ include "primehub.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
