{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.gitsync.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-gitsync
data:
  {{- tpl (.Files.Glob "hooks/gitsync/*").AsConfig . | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-gitsync-scripts
data:
  {{- tpl (.Files.Glob "scripts/gitsync/*").AsConfig . | nindent 2 }}
{{- end }}
{{- end }}
