{{- if eq .Values.primehub.mode "ee" }}
{{- if .Values.ingress.enabled -}}
{{- if .Values.istio.enabled -}}
{{- if .Values.adminNotebook.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "primehub.name" . }}-vs-admin-notebook
spec:
  hosts:
    {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
    {{- end}}
  gateways:
    - {{ include "primehub.name" . }}-gateway
  http:
    - match:
        - uri:
            prefix: /maintenance
      route:
        - destination:
            host: {{ include "primehub.name" . }}-admin-notebook.{{ .Release.Namespace }}.svc.cluster.local
            port:
                number: 80
{{- end}}
{{- end}}
{{- end}}
{{- end }}
