{{- if .Values.keycloak.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.postgresql.auth.username) }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.name" .) "key" "password" "providedValues" (list "postgresql.auth.password") "context" $) }}
  {{- end }}
{{- end -}}
