{{- if or (eq .Values.primehub.mode "ee") (eq .Values.primehub.mode "ce") }}
{{- if .Values.groupvolume.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-group
data:
  {{- tpl (.Files.Glob "hooks/groupvolume/group-pv.jsonnet").AsConfig . | nindent 2 }}
  {{- tpl (.Files.Glob "hooks/groupvolume/nfs-for-pvc.jsonnet").AsConfig . | nindent 2 }}
{{- end }}
{{- end }}
