{{- if or (eq .Values.primehub.mode "ee") (eq .Values.primehub.mode "ce") }}
{{- if .Values.groupvolume.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primehub-group
spec:
  replicas: {{ .Values.groupvolume.replicas }}
  selector:
    matchLabels:
      app: primehub-group
  template:
    metadata:
      labels:
        app: primehub-group
        role: webhook-server
      annotations:
        sidecar.istio.io/inject: "false"
        checksum/config: {{ tpl (.Files.Glob "hooks/groupvolume/*").AsConfig . | nindent 2 | sha256sum }}
    spec:
      containers:
      - name: hooks
        image: "{{ .Values.groupvolume.image.repository }}:{{ .Values.groupvolume.image.tag }}"
        imagePullPolicy: {{ .Values.groupvolume.image.pullPolicy }}
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        resources:
{{ toYaml .Values.groupvolume.resources | indent 10 }}
    {{- with .Values.groupvolume.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.groupvolume.affinity }}
      affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.groupvolume.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
      volumes:
      - name: hooks
        configMap:
          name: primehub-group
{{- end }}
{{- end }}
