---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instancetypes.primehub.io
spec:
  conversion:
    strategy: None
  group: primehub.io
  names:
    kind: InstanceType
    listKind: InstanceTypeList
    plural: instancetypes
    singular: instancetype
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        properties:
          metadata:
            type: object
          spec:
            properties:
              description:
                type: string
              displayName:
                type: string
              limits.cpu:
                type: number
              limits.memory:
                type: string
              limits.nvidia.com/gpu:
                type: integer
              requests.memory:
                type: string
              requests.cpu:
                type: number
              nodeSelector:
                x-kubernetes-preserve-unknown-fields: true
                type: object
              tolerations:
                type: array
                items:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
            required:
            - limits.cpu
            - limits.memory
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datasets.primehub.io
spec:
  conversion:
    strategy: None
  group: primehub.io
  names:
    kind: Dataset
    listKind: DatasetList
    plural: datasets
    singular: dataset
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        properties:
          metadata:
            type: object
          spec:
            properties:
              description:
                type: string
              displayName:
                type: string
              gitsync:
                properties:
                  secret:
                    type: string
                type: object
              hostPath:
                properties:
                  path:
                    type: string
                required:
                - path
                type: object
              nfs:
                properties:
                  path:
                    type: string
                  server:
                    type: string
                required:
                - server
                - path
                type: object
              pv:
                properties:
                  provisioning:
                    pattern: ^(auto|manual)$
                    type: string
                type: object
              type:
                pattern: ^(env|git|pv|hostPath|nfs)$
                type: string
              enableUploadServer:
                pattern: ^(true|false)$
                type: string
              url:
                type: string
              variables:
                x-kubernetes-preserve-unknown-fields: true
                type: object
              volumeName:
                type: string
            type: object
        type: object
    served: true
    storage: true

