#!/bin/bash

set -e

CHART_NAME=primehub
CHART_ROOT=$(dirname "${BASH_SOURCE[0]}")/../chart
PROJECT_ROOT=$(dirname "${BASH_SOURCE[0]}")/..

# it is registered into both circlie-ci and github
# by the way, circlie-ci only accept PEM private key format
# it should be generated by "ssh-keygen -m pem"
CI_PUBLISH_KEY=~/.ssh/id_rsa_d090279cdc28b53ed8180c9a64466fd4

source $PROJECT_ROOT/ci/common.sh

install::helm
install::chartpress
install::submodule
helm::update_dependency
ci::setup_ci_environment_and_publish
