{{- if or (eq .Values.primehub.mode "ee") (eq .Values.primehub.mode "ce") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primehub-metacontroller-webhook
spec:
  replicas: {{ .Values.metacontroller.webhook.replicas }}
  selector:
    matchLabels:
      app: primehub-metacontroller-webhook
  template:
    metadata:
      labels:
        app: primehub-metacontroller-webhook
        role: webhook-server
      annotations:
        sidecar.istio.io/inject: "false"
        checksum/config: {{ tpl (.Files.Glob "hooks/*/*").AsConfig . | nindent 2 | sha256sum }}
    spec:
      containers:
      - name: hooks
        image: "{{ .Values.metacontroller.webhook.image.repository }}:{{ .Values.metacontroller.webhook.image.tag }}"
        imagePullPolicy: {{ .Values.metacontroller.webhook.image.pullPolicy }}
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        resources:
{{ toYaml .Values.metacontroller.webhook.resources | indent 10 }}
    {{- with .Values.metacontroller.webhook.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.metacontroller.webhook.affinity }}
      affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.metacontroller.webhook.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
      volumes:
      - name: hooks
        configMap:
          name: primehub-metacontroller-webhook
{{- end }}
