{{- if .Values.console.image.credentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "primehub.console.pullSecret" . }}
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-console-pull-secret
type: kubernetes.io/dockerconfigjson
{{- end }}
