apiVersion: v1
kind: Service
metadata:
  name: {{ include "primehub.name" . }}-console
  labels:
    app.kubernetes.io/name: {{ include "primehub.name" . }}-console
    helm.sh/chart: {{ include "primehub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.console.service.type }}
  ports:
    - port: {{ .Values.console.service.port }}
      targetPort: {{ .Values.console.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "primehub.name" . }}-console
    app.kubernetes.io/instance: {{ .Release.Name }}
