apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "primehub.name" . }}-watcher
rules:
- apiGroups:
  - primehub.io
  resources:
  - instancetypes
  - images
  - datasets
  verbs:
  - get
  - watch
  - list
- apiGroups: [""]
  resources:
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "primehub.name" . }}-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "primehub.name" . }}-watcher
subjects:
- kind: ServiceAccount
  name: {{ include "primehub.name" . }}-watcher
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "primehub.name" . }}-watcher
  labels:
    app: {{ include "primehub.name" . }}
    chart: {{ include "primehub.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
