{{- if .Values.watcher.image.credentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "primehub.watcher.pullSecret" . }}
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-watcher-pull-secret
type: kubernetes.io/dockerconfigjson
{{- end }}
