name: "Build PrimeHub Chart Release Tarball"
on:
  release:
    types:
      - created

jobs:
  build_release_tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Stop when see :latest
        run: |
          # check images.yaml
          count="$(grep -c :latest ./chart/images.yaml || true)"
          if [ "0" != $count ]; then
            echo ":latest tag cannot be used for release"
            grep -A3 -B3 :latest ./chart/images.yaml
            false
          fi

          # check values.yaml
          count="$(grep -c latest ./chart/values.yaml || true)"
          if [ "0" != $count ]; then
            echo ":latest tag cannot be used for release"
            grep -A3 -B3 latest ./chart/values.yaml
            false
          fi

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: Build Release Tarball
        run: |
          ./ci/release.sh
      - name: Upload Release Tarball
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: primehub-${{ github.event.release.tag_name }}.tar.gz
          asset_name: primehub-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/tar+gzip
