apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-hub-templates
data:
{{ (.Files.Glob "scripts/jupyterhub/theme/templates/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-hub-js
data:
{{ (.Files.Glob "scripts/jupyterhub/theme/static/js/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-hub-css
data:
{{ (.Files.Glob "scripts/jupyterhub/theme/static/css/primehub/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-hub-images
binaryData:
  PrimeHub.png: |-
    {{ (.Files.Get "scripts/jupyterhub/theme/static/images/PrimeHub.png") | b64enc }}
  primehub-logo.png: |-
    {{ (.Files.Get "scripts/jupyterhub/theme/static/images/primehub-logo.png") | b64enc }}
  clippy.svg: |-
    {{ (.Files.Get "scripts/jupyterhub/theme/static/images/clippy.svg") | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-hub-config
data:
{{ (.Files.Glob "scripts/jupyterhub/config/*").AsConfig | indent 2 }}
  values.yaml: |
    baseUrl: /
    version: {{ .Chart.AppVersion | quote }}
    graphqlEndpoint: {{ include "primehub.graphql.endpoint" . }}
    phfsEnabled: {{ include "primehub.phfs.enabled" . }}
    phfsPVC: {{ include "primehub.store.pvcName" . }}
    grantSudo: {{ .Values.primehub.grantSudo }}
    keycloak:
      url: {{ include "primehub.keycloak.url" . }}
      appUrl: {{ include "primehub.keycloak.appUrl" . }}
      realm: {{ .Values.primehub.keycloak.realm }}
      clientId: {{ include "primehub.jupyterhub.clientId" . }}
      {{- if .Values.primehub.keycloak.rolePrefix }}
      rolePrefix: {{ .Values.primehub.keycloak.rolePrefix | quote }}
      {{- end}}
    sshServer:
      enabled: {{ .Values.sshBastionServer.enabled }}
      servicePort: {{ .Values.sshBastionServer.service.port }}
      {{- if .Values.sshBastionServer.customHostname }}
      customHostname: {{ .Values.sshBastionServer.customHostname }}
      {{- end}}
    host: {{ index .Values.ingress.hosts 0 }}
    telemetry:
      enabled: {{ .Values.telemetry.enabled }}
    {{- .Values.jupyterhub.primehub | toYaml | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: start-notebook-d
data:
{{ (.Files.Glob "scripts/start-notebook.d/*").AsConfig | indent 2 }}
{{- if .Values.jupyterhub.primehub.startnotebook }}
{{- range $key, $val := .Values.jupyterhub.primehub.startnotebook }}
{{ print "custom-" $key | indent 2 }}: |
{{ $val | indent 4 }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-version
data:
  version: {{ .Chart.AppVersion | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-start-notebook
data:
{{ (.Files.Glob "scripts/primehub-start-notebook/*").AsConfig | indent 2 }}
